trigger: none

pool: 
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'devops-sub'
  resourceGroupName: 'bkrgtf-eus2'
  terraformDirectory: 'terraformvm2'
  vmName: 'vmcheck'



steps:
  - task: TerraformInstaller@1
    displayName: 'Terraform Installer' 
    inputs:
      terraformVersion: 'latest'

  - task: AzureCLI@2
    displayName: 'Terraform Init & check VM'
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: '$(terraformDirectory)'
      inlineScript: |
        terraform init

        echo "checking RG: $(resourceGroupName)"

        EXISTS=$(az group exists \
        --name "$(resourceGroupName)")

        if [ "$EXISTS" = "true" ]; then

          echo "RG already exists."
          
          RG_ID=$(az group show \
          --name "$(resourceGroupName)" \
          --query id \
          -o tsv)

          echo "importing existing RG group into Terraform statefile"
          terraform import \
          azurerm_resource_group.rg \
          "$RG_ID" || echo "imported RG successfully"

        else
          
          echo "RG doesn't exist"
          echo "terraform creating RG"
        
        fi

        echo "Checking VM: $(vmName)"
        echo "Resource Group: $(resourceGroupName)"
        EXISTS=$(az vm show \
        --name "$(vmName)" \
        --resource-group "$(resourceGroupName)" \
        --query name \
        -o tsv)

        if [ "$EXISTS" = "$(vmName)" ]; then
          echo "VM already exists."
          echo "importing existing VM into Terraform statefile"
          VM_ID=$(az vm show \
          --name "$(vmName)" \
          --resource-group "$(resourceGroupName)" \
          --query id \
          -o tsv)
          
          terraform import \
          azurerm_linux_virtual_machine.vmcheck \
          "$VM_ID" || echo "imported VM successfully"

        else
          
          echo "VM doesn't exist"
          echo "terraform creating VM"
        
        fi

  - task: AzureCLI@2
    displayName: 'Terraform Plan'
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: '$(terraformDirectory)'
      inlineScript: |
        terraform plan -out=tfplan

  - task: AzureCLI@2
    displayName: 'Terraform Apply'
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: '$(terraformDirectory)'
      inlineScript: |
        terraform apply -auto-approve tfplan